### ISSUE TITLE
no file

### ISSUE THREAD

**Issue by wendy0527** [ziyc/drivestudio#11]
`
class HMR2023TextureSampler(HMR2Predictor):
    def __init__(self, cfg) -> None:
        super().__init__(cfg)
        bmap = np.load(os.path.join(CACHE_DIR, 'phalp/3D/bmap_256.npy'))
        fmap = np.load(os.path.join(CACHE_DIR, 'phalp/3D/fmap_256.npy'))
`
I want to preprocess my own dataset, but where can I download these two files? I couldn't find at https://github.com/shubham-goel/4D-Humans.

**Comment by ziyc** [comment]
Hi @wendy0527,

These files should download automatically in the code. If they're missing, it may be due to network issues. Check your connection to ensure it can download the data.

These files aren't directly available on the 4D-Humans repo. They might be downloaded by one of  4D-Humans' dependencies.

If you're seeing download errors, you can share the error messages, that would be helpful for me to figure out the problem.
