### ISSUE TITLE
Try to add nuscenes radar source to gaussian initialization

### ISSUE THREAD

**Issue by chloexiangyy** [ziyc/drivestudio#62]
Hi! I am trying to add nuscenes radar source to gaussian initialization, but I got ValueError: NaN detected in loss Background_sharp_shape_reg at step 0 at the very begining. Has somebody tried this?

**Comment by wzy-99** [comment]
I encountered the same problem.

I found it is because some background cloud points are very close, which caused the scale to -inf when creating from dataset.

https://github.com/ziyc/drivestudio/blob/388642a6a998833cb388e0f1a65dfc2071cc6a61/models/gaussians/vanilla.py#L82-L92

![image](https://github.com/user-attachments/assets/058911e9-5373-4e15-8e65-277bce87e0e5)

![image](https://github.com/user-attachments/assets/c3a8612c-fea9-491f-996d-c6c6e1edf6be)

My solution is clamping the `avg_dist`:

```python
avg_dist = avg_dist.clamp_min(1e-3)
```

It works fine for me.
