### ISSUE TITLE
Preparing Waymo Open Dataset: Step 2: The system cannot find the file specified

### ISSUE THREAD

**Issue by takathelunatic** [ziyc/drivestudio#7]
hi I'm preparing the Waymo Open Dataset, however after setting Waymo account and installing Gcloud SDK I couldn't finish step 2: "Download the Raw Data"
Upon typing:
> python datasets/waymo/waymo_download.py \
>     --target_dir ./data/waymo/raw \
>     --split_file data/waymo_example_scenes.txt

I got this error:

> (base) PS D:\Github repo\drivestudio> python datasets\waymo\waymo_download.py     --target_dir .\data\waymo\raw     --split_file data\waymo_example_scenes.txt
> note: `gcloud auth login` is required before running this script
> Downloading Waymo dataset from Google Cloud Storage...
> [1/8] Failed to download. Error: [WinError 2] The system cannot find the file specified
> [2/8] Failed to download. Error: [WinError 2] The system cannot find the file specified
> [3/8] Failed to download. Error: [WinError 2] The system cannot find the file specified
> [4/8] Failed to download. Error: [WinError 2] The system cannot find the file specified
> [5/8] Failed to download. Error: [WinError 2] The system cannot find the file specified
> [6/8] Failed to download. Error: [WinError 2] The system cannot find the file specified
> [7/8] Failed to download. Error: [WinError 2] The system cannot find the file specified
> [8/8] Failed to download. Error: [WinError 2] The system cannot find the file specified

**Comment by ziyc** [comment]
Hey @takathelunatic, have you first logged into gcloud by typing gcloud auth login? If you did and still have this issue, it might be due to network problems. Can you try ping google.com to check if you can connect to Google's networks? If all these don't work, you can manually download the `.tfrecord` files from Waymo's Google Cloud site and put them under `./data/waymo/raw`.

Also, are you running our code on Windows? We haven't tested our code on Windows, so I'm not sure if this is due to Windows-specific issues.
